server:
  port: 8080
  
spring:
  application:
    name: gateway
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: gateway
      profile: dev
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'