server:
  port: 8081
    
spring:
  application:
    name: front
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: frontweb
      profile: dev
      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'