server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

spring:
  application:
    name: discovery
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: discovery
      profile: dev
          
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'        